version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: pg
    versions:
    - 8.5.1
    - 8.6.0
  - dependency-name: winston
    versions:
    - 3.3.3
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
    - 7.23.2
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: knex
    versions:
    - 0.21.16
    - 0.21.17
    - 0.21.18
    - 0.21.19
    - 0.95.0
    - 0.95.1
    - 0.95.2
    - 0.95.3
    - 0.95.4
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: express-winston
    versions:
    - 4.0.5
    - 4.1.0
  - dependency-name: eslint-plugin-jsx-a11y
    versions:
    - 6.4.1
  - dependency-name: eslint
    versions:
    - 7.6.0
  - dependency-name: eslint-config-airbnb
    versions:
    - 18.2.0
